language: php
php:
- 5.6
before_script:
- composer install
- export PATH=./vendor/bin/:$PATH
- git config --global credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script:
- bash .travis-generate-docs.sh
notifications:
  slack:
    secure: hZn8msOcBV96Z+YKNZ5yt6/rv0CtD8yj5KEsdZAIbKlSoCB4QBh+RNlyfuBUJ1SbodxBU4v4Yyln8VbavysZ1l4INZEEcNRto+/vjQDLHNLWwSJ4u1tg0vNE29CNIQsaJ4Vd/ZplC6yX9H7S8SEF81Zuz57wTcmRMhY6371kezg=
env:
  global:
  - secure: ZCoO8vC5W3k+V3vb7uxsZtROjdikHCxNbvE1ptTvRWjq9tJS9LV5gQVM6f+FNylgPgcQL9qzhd4krrh8fNuriuRotqWd35XH9FW1ISzSMpkADpwDM2t/az/dhucRKc43eDqW8d/XrrvrmqsTYe694jd+lrvcimGeFw0WEfXIHBk=
